### PR TITLE
Add support for DWARF type import.

### LINKED ISSUE #1: Add support for DWARF type import
Webassembly supports embedding of DWARF debug information ([documentation](https://yurydelendik.github.io/webassembly-dwarf/)) and most compiler toolchain (rust, emscripten) already support this.

DWARF section are stored as WASM custom section with the corresponding DWARF section name.

Ghidra provides a `DWARFAnalyzer` that can be reused with very little effort to extract DataTypes and function signatures.
There are specificities in the way Wasm function offset and variable location are described in DWARF that would require changes deep in the current ghidra DWARF parsing to make the "Function import"functionality  work so they will be listed in a separate issue.

All that is required to enable DWARF parsing is:
* provide a subclass of `DWARFAnalyzer` that override `canAnalyse()` to support Webassembly.
* define a `DWARFSectionProvider` to provide access to DWARF section content from their name.

I can see two ways this could be implemented with the current code base:

**Option 1**
Create new memory blocks for each custom wasm section using the custom section name as block name and strip the wasm section header.
 
PROS:
* This would match the default behavior for ELF file so the default BaseSectionProvider could be used and the custom `DWARFAnalyzer` would be simple ([example](https://github.com/cmorin6/ghidra-wasm-plugin/blob/master/src/main/java/wasm/analysis/dwarf/WasmDWARFAnalyzer.java))

CONS:
* custom sections content would be duplicated

**Option 2**
Create a custom `DWARFSectionProvider` that map DWARF section to the corresponding wasm custom section.

PROS:
* No changes to the current WasmLoader
* Since we need to duplicate the code of the DWARFAnalyzer to use our custom DWARFSectionProvider, we can remove the "import functions" options that can't be supported easily at the moment but is set to true by default. This would avoid the error message upon analysis if the "import functions" is left to to true.

CONS:
* Duplication of the code of DWARFAnalyzer (~250 line) to use our custom DWARFSectionProvider. Since most of the fields of DWARFAnalyzer are private we would need to duplicate most of the code which would be ugly and harder to maintain.
* the custom `DWARFSectionProvider` would need access to a `WasmModule` instance (probably from `WasmAnalysis`) to map wasm section to DWARF ones. The `DWARFAnalyzer` checks for the presence of sections in it's `canAnalyze()`. This would mean that the `WasmAnalysis` and `WasmModule` would need to be initialized, parsing the module structure, just to know if the `DWARFAnalyzer` should be enabled.

I can make a merge request for this if needed.

### PR DESCRIPTION
**Pull request by cmorin6**
This should allow datatype import from DWARF sections.

[Here](https://github.com/nneonneo/ghidra-wasm-plugin/files/7313374/dwarf.zip) is a minimal sample https://webassembly.studio/ project for testing.

As discussed in the original issue #1 only data types and function signatures are imported at the moment.

For the function signatures to be applied you need to select manually `DataType > {your_wasm_file} > Apply Function Data Types` from the `Data Type Manager` window.

Also if the `import function` option is left to true (the default value) an error windows will be displayed at the end of the analysis to inform that the function import failed.

Fixes #1

### CODE REVIEW

**Comment by nneonneo** [comment]
Neat. It looks like it works decently well. I did get the following message on startup:

    No DWARF to Ghidra register mappings found for this program's language [Wasm:LE:32:default], unable to import functions.

Why is that? Could we define a register mapping (even maybe a dummy one?) so this message box will go away?

**Comment by nneonneo** [comment]
Any update on the register mapping issue? I think that's the only thing that should be resolved to merge the PR.

**Comment by cmorin6** [comment]
Sorry, it seems that I just missed the release.

I added a dummy register mapping file which removed the error message.
You will still get some ugly stack traces in the console if you run DWARF analysis with the "import functions" option enable, (since Wasm does weird things with DWARF format which prevent automatic import of functions) but they shouldn't have any impact.

Adding the dummy register mapping seems to have enabled import of global variables (name + type) which are now automatically marked by the DWARF Analyzer.

**Comment by nneonneo** [comment]
I do not completely understand how DWARF PC addresses are supposed to map to file offsets. I sort of assumed that DWARF address zero was the address of the first instruction of the first function, which mostly works, but for some functions it's not quite right (off by a few bytes). If there's a good reference for how the DWARF PC addresses are computed from the file content, that'd be wonderful.

It's possible to adjust the PCs so that function import works, by setting an obscure program property called `ElfLoader.ELF_ORIGINAL_IMAGE_BASE_PROPERTY` (this can be set even if the file is not an ELF). The difference between the property value and the program's loaded base address (set to 0x80000000 in the current loader) will be added to each DWARF PC property.

Right now, unfortunately, with the *default* DWARF import settings, we get crashes and the Wasm analyzer fails with an NPE. That's easy enough to fix, but the underlying issue is that the default settings result in functions being imported at totally bogus addresses; those functions get sent to the analyzer, which promptly chokes. It'd be really nice to figure out how to get function import to work properly so we didn't have this issue. Ideally, the plugin should never crash or misbehave if users use the default analysis options on a file.

**Comment by nneonneo** [comment]
...so I'm thinking that we have two not-mutually-exclusive options now:

1. In order to support DWARF PCs at all, we need to set the `ElfLoader.ELF_ORIGINAL_IMAGE_BASE_PROPERTY` so that the DWARF loader will populate the debug information at the correct addresses.
2. To support DWARF function definitions, which is useful since the DWARF function definitions will come with proper function types, we need to (incompatibly) extend the definition of a function in Ghidra to include the locals. In actuality, the WebAssembly spec already suggests that the function's code block includes the locals definitions because the locals definitions are included in the size of the function body. So, this change would have functions begin at the locals count, and then some SLEIGH changes + analyzer changes would be needed to ensure that the locals are parsed correctly (and not as instructions!)

Both are reasonable, but option 2 would be an incompatible change so it'd probably require a version bump - it would not be possible to load an existing project using the new plugin.

**Comment by cmorin6** [comment]
I wasn't aware of the `ElfLoader.ELF_ORIGINAL_IMAGE_BASE_PROPERTY` but it seems that it would be used for everything and would then cause issues with the global variables address.

Even if we did both the options you described, there is still an issue because WASM defines its [own location DWARF opcode ](https://yurydelendik.github.io/webassembly-dwarf/#DWARF-expressions-and-location-descriptions).
This throws an exception [here](https://github.com/NationalSecurityAgency/ghidra/blob/c19276091f274a9ef0850c904c743f61c850854e/Ghidra/Features/Base/src/main/java/ghidra/app/util/bin/format/dwarf4/next/DWARFFunctionImporter.java#L234) and prevent the function from being imported.

I tested this with a local branch that copies most of the DWARF parsing code that intercept parsed functions and override their address with the correct location. I only managed to get function import working by commenting the line described above.

I don't think there is a clean way to get DWARF function import working without modifying the DWARF import cod. That's why I originally wanted to only support data type import first.

If this works for you, perhaps an option would be to override the DWARFAnalyzer completely and remove the function import option to effectively disable the functionality an thus prevent the error popup. Function data-types would need to be applied manually after DWARF analysis (`DataType > {your_wasm_file} > Apply Function Data Types` from the Data Type Manager window).

**Comment by nneonneo** [comment]
@cmorin6 Thanks for putting this PR together, and sorry for leaving it for so long! If you're still interested in the PR, I would be happy to accept it with just the data type components without the function stuff. This would ideally also end up as part of the upstream PR: https://github.com/NationalSecurityAgency/ghidra/pull/4103

There should ideally only be minimal changes necessary to support the latest v2.0.0 code changes. If you don't have time/energy to do these changes I'd be happy to look into them as well.

**Comment by cmorin6** [comment]
Sorry for the late answer.

Unfortunatelly I won't have the time to work on this until a couple of weeks. So feel free to work on this as you please.

Nice work putting the upsteam PR together. Congrats !

**Comment by nneonneo** [comment]
It turns out that I actually built the upstream PR, and the "2.0" version, on top of this PR (and the `include_locals` fix). So it was, in a sense, already merged :)

**Pull request merged**
